### ISSUE TITLE
Unable to install import Bourbon on Ember 0.2.2

### ISSUE THREAD

**Issue by BenMorganIO** [yapplabs/ember-cli-bourbon#4]
Node: 0.12.0
npm: 2.7.4
Ember: 0.2.2

Steps to reproduce:

1. Setup an ember cli project with Ember 0.2.2
2. Run `npm install ember-cli-bourbon --save-dev`
3. Run `ember s`

Expected Result: Successful compile with no deprecation warnings.
Given Result:

```
$ ember s
version: 0.2.2
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-cli-bourbon]
Livereload server on port 35729
Serving on http://localhost:4200/

ENOENT, no such file or directory '/Users/benmorgan/Sites/ember_app/frontend/tmp/funnel-dest_fJP49r.tmp/'
Error: ENOENT, no such file or directory '/Users/benmorgan/Sites/ember_app/frontend/tmp/funnel-dest_fJP49r.tmp/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:765:18)
    at /Users/benmorgan/Sites/ember_app/frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:32:21
    at Array.map (native)
    at mergeRelativePath (/Users/benmorgan/Sites/ember_app/frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:29)
    at /Users/benmorgan/Sites/ember_app/frontend/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
    at lib$rsvp$$internal$$tryCatch (/Users/benmorgan/Sites/ember_app/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/benmorgan/Sites/ember_app/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/benmorgan/Sites/ember_app/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/benmorgan/Sites/ember_app/frontend/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
```

**Comment by BenMorganIO** [comment]
`this.pickFiles` appears to be coming from [here](https://github.com/yapplabs/ember-cli-bourbon/blob/master/index.js#L13).

**Comment by stefanpenner** [comment]
should be fixed  by: https://github.com/yapplabs/ember-cli-bourbon/pull/6

**Comment by lukemelia** [comment]
New release should fix ya!
